name: Sonar Report

on:
  workflow_dispatch:

jobs:
  sonar-report:
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch SonarCloud metrics
        run: |
          curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
          "https://sonarcloud.io/api/measures/component?component=tahaather07_Softly-Roguelike&metricKeys=complexity,cognitive_complexity,duplicated_lines_density,coverage,branch_coverage,bugs,vulnerabilities,code_smells,sqale_index,sqale_rating" \
          -o sonar_report.json

      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonar-report
          path: sonar_report.json
